baseURL = "https://zaracooper.github.io/blog/"
languageCode = "en-us"
title = "Zara's Code Adventures"
theme = "tale"
disqusShortname = "zaracooper-github-io"

[Author]
    name = "Zara"

[Params]
[[Params.links]]
    type = "image/png"
    href = "images/logo.png"
    rel = "icon"
    critical = "true"

[[Params.links]]
    type = "text/css"
    href = "css/styling.css"
    rel = "stylesheet"

[[Params.links]]
    type = "text/css"
    href = "css/prism.css"
    rel = "stylesheet"

[[Params.scripts]]
    type = "text/javascript"
    src = "scripts/prism.js"
    async = "true"